theme: minima  # Стандартная тема
markdown: kramdown
kramdown:
  input: GFM           # Поддержка GitHub Flavored Markdown
  math_engine: mathjax # Для формул LaTeX
plugins:
  - jekyll-feed
  
# Меню сайта
navigation:
  - title: "Главная"
    url: "/"
  - title: "Валидатор"
    url: "/test_agpolma.github.io/#:~:text=%D0%9E%20%D1%81%D0%B0%D0%B9%D1%82%D0%B5-,%D0%92%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D1%80,-%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D1%83%20%D1%81%D0%B2%D0%BE%D0%B8%D1%85%20%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B9"
