title: BIA Technologies
description: Описание
theme: minima  # Стандартная тема
markdown: kramdown
plugins:
  - jekyll-feed
author: 2025
minima:
  skin: classic 
  skin_primary: "#ffffff" # Белый фон шапки
  skin_border: "#e5e5e5" # Граница
